FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    liblz4-dev \
    libsnappy-dev \
    curl \
    netcat-openbsd \
    procps \
    default-jre-headless \
    && rm -rf /var/lib/apt/lists/*


ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH="${JAVA_HOME}/bin:${PATH}"


COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 7860

ENTRYPOINT ["./entrypoint.sh"]
