FROM apache/spark:latest

USER root


RUN cd /opt/spark/jars && \
    curl -L -O "https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.6.0/kafka-clients-3.6.0.jar" && \
    curl -L -O "https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.13/4.0.0/spark-sql-kafka-0-10_2.13-4.0.0.jar" && \
    curl -L -O "https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.13/4.0.0/spark-token-provider-kafka-0-10_2.13-4.0.0.jar" && \
    curl -L -O "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.12.0/commons-pool2-2.12.0.jar"


RUN mkdir -p /opt/spark/conf && \
    echo "spark.driver.bindAddress 0.0.0.0" >> /opt/spark/conf/spark-defaults.conf

USER root

